import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { setAIProvider } from "@/server/ai";
import type { ChatMessage } from "@/server/ai/provider";
import { editSummary, generateSummary, listSummaries, releaseSummary } from "@/server/services/summaries";
import type { User, Question, EvaluationRound, Team, Course } from "@/generated/prisma/client";
import {
  createCourse, createOpenRound, createProfessor, createQuestions, createTeamWithStudents,
  PAGE1, resetDb, submitFor,
} from "./helpers";

let course: Course;
let actorId: string;
let joe: User, peter: User, sarah: User;
let team: Team;
let rating: Question;
let round: EvaluationRound;
let captured: ChatMessage[][] = [];

beforeEach(async () => {
  await resetDb();
  captured = [];
  setAIProvider({
    model: "fake-model",
    async complete(messages) {
      captured.push(messages);
      return "Summary: teamwork is improving.";
    },
  });
  course = await createCourse();
  actorId = (await createProfessor(course.id)).id;
  const alpha = await createTeamWithStudents(course.id, "Alpha", ["Joe", "Peter", "Sarah"]);
  [joe, peter, sarah] = alpha.students as [User, User, User];
  team = alpha.team;
  ({ rating } = await createQuestions(course.id));
  round = await createOpenRound(course.id);
  await submitFor(joe.id, round.id, [peter.id, sarah.id], rating.id, 4, "Peter interrupts a lot");
  await submitFor(peter.id, round.id, [joe.id, sarah.id], rating.id, 3, "Joe is very supportive");
});

afterEach(() => setAIProvider(null));

describe("generateSummary", () => {
  it("stores a round summary generated by the provider", async () => {
    const summary = await generateSummary(
      { roundId: round.id, subjectType: "ROUND", kind: "INSTRUCTOR" },
      course.id,
      actorId,
    );
    expect(summary.content).toContain("teamwork is improving");
    expect(summary.model).toBe("fake-model");
    expect((await listSummaries(course.id, PAGE1, round.id)).items).toHaveLength(1);
  });

  it("scopes comments to a student and never includes evaluator identities", async () => {
    await generateSummary(
      { roundId: round.id, subjectType: "STUDENT", subjectId: peter.id, kind: "STUDENT_FEEDBACK" },
      course.id,
      actorId,
    );
    const prompt = captured[0]!.map((m) => m.content).join("\n");
    expect(prompt).toContain("Peter interrupts a lot");
    expect(prompt).not.toContain("Joe is very supportive"); // other student's feedback
    // Evaluator names are never sent to the AI provider.
    expect(prompt).not.toMatch(/evaluator/i);
  });

  it("scopes comments to a team", async () => {
    await generateSummary(
      { roundId: round.id, subjectType: "TEAM", subjectId: team.id, kind: "COMPLAINTS" },
      course.id,
      actorId,
    );
    const prompt = captured[0]!.map((m) => m.content).join("\n");
    expect(prompt).toContain("Peter interrupts a lot");
    expect(prompt).toContain("Joe is very supportive");
  });

  it("requires subjectId for TEAM/STUDENT scopes", async () => {
    await expect(
      generateSummary({ roundId: round.id, subjectType: "STUDENT", kind: "POSITIVES" }, course.id, actorId),
    ).rejects.toThrow("subjectId is required");
  });

  it("fails cleanly when there are no comments", async () => {
    const empty = await db.evaluationRound.create({
      data: { courseId: course.id, name: "Sprint 9", sprint: 9, status: "OPEN" },
    });
    await expect(
      generateSummary({ roundId: empty.id, subjectType: "ROUND", kind: "POSITIVES" }, course.id, actorId),
    ).rejects.toThrow("No comments");
  });
});

describe("editSummary", () => {
  async function draftFor(kind: "INSTRUCTOR" | "STUDENT_FEEDBACK" = "STUDENT_FEEDBACK") {
    return generateSummary(
      { roundId: round.id, subjectType: "STUDENT", subjectId: peter.id, kind },
      course.id,
      actorId,
    );
  }

  it("revises a draft's text and stamps editedAt", async () => {
    const summary = await draftFor();
    expect(summary.editedAt).toBeNull();
    const updated = await editSummary(summary.id, course.id, actorId, "  Instructor-revised feedback.  ");
    expect(updated.content).toBe("Instructor-revised feedback."); // trimmed
    expect(updated.editedAt).toBeInstanceOf(Date);
  });

  it("refuses to edit a released summary", async () => {
    const summary = await draftFor();
    await releaseSummary(summary.id, course.id, actorId);
    await expect(
      editSummary(summary.id, course.id, actorId, "too late"),
    ).rejects.toThrow("already been released");
  });

  it("rejects empty content", async () => {
    const summary = await draftFor();
    await expect(editSummary(summary.id, course.id, actorId, "   ")).rejects.toThrow("can't be empty");
  });

  it("404s for a summary in another course", async () => {
    const summary = await draftFor();
    const other = await createCourse();
    await expect(
      editSummary(summary.id, other.id, actorId, "nope"),
    ).rejects.toThrow("Summary not found");
  });
});
