import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { setAIProvider } from "@/server/ai";
import type { ChatMessage } from "@/server/ai/provider";
import { generateSummary, listSummaries } from "@/server/services/summaries";
import type { User, Question, EvaluationRound, Team } from "@/generated/prisma/client";
import {
  createOpenRound, createProfessor, createQuestions, createTeamWithStudents, resetDb, submitFor,
} from "./helpers";

let actorId: string;
let joe: User, peter: User, sarah: User;
let team: Team;
let rating: Question;
let round: EvaluationRound;
let captured: ChatMessage[][] = [];

beforeEach(async () => {
  await resetDb();
  captured = [];
  setAIProvider({
    model: "fake-model",
    async complete(messages) {
      captured.push(messages);
      return "Summary: teamwork is improving.";
    },
  });
  actorId = (await createProfessor()).id;
  const alpha = await createTeamWithStudents("Alpha", ["Joe", "Peter", "Sarah"]);
  [joe, peter, sarah] = alpha.students as [User, User, User];
  team = alpha.team;
  ({ rating } = await createQuestions());
  round = await createOpenRound();
  await submitFor(joe.id, round.id, [peter.id, sarah.id], rating.id, 4, "Peter interrupts a lot");
  await submitFor(peter.id, round.id, [joe.id, sarah.id], rating.id, 3, "Joe is very supportive");
});

afterEach(() => setAIProvider(null));

describe("generateSummary", () => {
  it("stores a round summary generated by the provider", async () => {
    const summary = await generateSummary(
      { roundId: round.id, subjectType: "ROUND", kind: "INSTRUCTOR" },
      actorId,
    );
    expect(summary.content).toContain("teamwork is improving");
    expect(summary.model).toBe("fake-model");
    expect(await listSummaries(round.id)).toHaveLength(1);
  });

  it("scopes comments to a student and never includes evaluator identities", async () => {
    await generateSummary(
      { roundId: round.id, subjectType: "STUDENT", subjectId: peter.id, kind: "STUDENT_FEEDBACK" },
      actorId,
    );
    const prompt = captured[0]!.map((m) => m.content).join("\n");
    expect(prompt).toContain("Peter interrupts a lot");
    expect(prompt).not.toContain("Joe is very supportive"); // other student's feedback
    // Evaluator names are never sent to the AI provider.
    expect(prompt).not.toMatch(/evaluator/i);
  });

  it("scopes comments to a team", async () => {
    await generateSummary(
      { roundId: round.id, subjectType: "TEAM", subjectId: team.id, kind: "COMPLAINTS" },
      actorId,
    );
    const prompt = captured[0]!.map((m) => m.content).join("\n");
    expect(prompt).toContain("Peter interrupts a lot");
    expect(prompt).toContain("Joe is very supportive");
  });

  it("requires subjectId for TEAM/STUDENT scopes", async () => {
    await expect(
      generateSummary({ roundId: round.id, subjectType: "STUDENT", kind: "POSITIVES" }, actorId),
    ).rejects.toThrow("subjectId is required");
  });

  it("fails cleanly when there are no comments", async () => {
    const empty = await db.evaluationRound.create({
      data: { name: "Sprint 9", sprint: 9, status: "OPEN" },
    });
    await expect(
      generateSummary({ roundId: empty.id, subjectType: "ROUND", kind: "POSITIVES" }, actorId),
    ).rejects.toThrow("No comments");
  });
});
